Selenium Gauge Test
=====================


Splice Beatmaker
-------------------------------
* OPEN
* SET BPM 90
* CREATE STRAIGHT PATTERN
* RANDOM BPM
* CREATE STRAIGHT PATTERN
* RANDOM BPM
* CREATE STRAIGHT PATTERN
* RANDOM BPM
* CREATE STRAIGHT PATTERN
* RANDOM BPM
* CREATE LAST STRAIGHT PATTERN
* LISTEN
* SAVE